import request from './request'

export const login = (data) => request.post('/auth/login', data)
export const getUserInfo = () => request.get('/auth/info')
export const changePassword = (data) => request.put('/auth/password', data)
export const updateProfile = (data) => request.put('/auth/profile', data)

export const tenantPage = (params) => request.get('/portal/tenant/page', { params })
export const createTenant = (data) => request.post('/portal/tenant', data)
export const updateTenant = (id, data) => request.put(`/portal/tenant/${id}`, data)
export const deleteTenant = (id) => request.delete(`/portal/tenant/${id}`)

export const userPage = (params) => request.get('/portal/user/page', { params })
export const createUser = (data) => request.post('/portal/user', data)
export const updateUser = (id, data) => request.put(`/portal/user/${id}`, data)
export const deleteUser = (id) => request.delete(`/portal/user/${id}`)
export const lockUser = (id, status) => request.put(`/portal/user/${id}/lock`, null, { params: { status } })

export const roleList = () => request.get('/portal/role/list')
export const rolePage = (params) => request.get('/portal/role/page', { params })
export const createRole = (data) => request.post('/portal/role', data)
export const updateRole = (id, data) => request.put(`/portal/role/${id}`, data)
export const deleteRole = (id) => request.delete(`/portal/role/${id}`)

export const deptTree = () => request.get('/portal/dept/tree')
export const createDept = (data) => request.post('/portal/dept', data)
export const updateDept = (id, data) => request.put(`/portal/dept/${id}`, data)
export const deleteDept = (id) => request.delete(`/portal/dept/${id}`)

export const menuTree = (params) => request.get('/portal/menu/tree', { params })
export const createMenu = (data) => request.post('/portal/menu', data)
export const updateMenu = (id, data) => request.put(`/portal/menu/${id}`, data)
export const deleteMenu = (id) => request.delete(`/portal/menu/${id}`)

export const logPage = (params) => request.get('/portal/log/page', { params })

export const dashboardStats = () => request.get('/dashboard/stats')

export const datasourcePage = (params) => request.get('/aggregation/datasource/page', { params })
export const datasourceList = () => request.get('/aggregation/datasource/list')
export const createDatasource = (data) => request.post('/aggregation/datasource', data)
export const updateDatasource = (id, data) => request.put(`/aggregation/datasource/${id}`, data)
export const deleteDatasource = (id) => request.delete(`/aggregation/datasource/${id}`)

export const incrementPage = (params) => request.get('/aggregation/increment/page', { params })
export const createIncrement = (data) => request.post('/aggregation/increment', data)
export const updateIncrement = (id, data) => request.put(`/aggregation/increment/${id}`, data)
export const deleteIncrement = (id) => request.delete(`/aggregation/increment/${id}`)

export const dataflowPage = (params) => request.get('/aggregation/dataflow/page', { params })
export const createDataflow = (data) => request.post('/aggregation/dataflow', data)
export const updateDataflow = (id, data) => request.put(`/aggregation/dataflow/${id}`, data)
export const deleteDataflow = (id) => request.delete(`/aggregation/dataflow/${id}`)
export const executeDataflow = (id) => request.post(`/aggregation/dataflow/${id}/execute`)

export const monitorStats = () => request.get('/aggregation/monitor/stats')

export const fullsyncPage = (params) => request.get('/aggregation/fullsync/page', { params })
export const createFullsync = (data) => request.post('/aggregation/fullsync', data)
export const updateFullsync = (id, data) => request.put(`/aggregation/fullsync/${id}`, data)
export const deleteFullsync = (id) => request.delete(`/aggregation/fullsync/${id}`)

export const cdcPage = (params) => request.get('/aggregation/cdc/page', { params })
export const createCdc = (data) => request.post('/aggregation/cdc', data)
export const updateCdc = (id, data) => request.put(`/aggregation/cdc/${id}`, data)
export const startCdc = (id) => request.post(`/aggregation/cdc/${id}/start`)
export const stopCdc = (id) => request.post(`/aggregation/cdc/${id}/stop`)
export const deleteCdc = (id) => request.delete(`/aggregation/cdc/${id}`)

export const appPage = (params) => request.get('/service/application/page', { params })
export const createApp = (data) => request.post('/service/application', data)
export const updateApp = (id, data) => request.put(`/service/application/${id}`, data)
export const deleteApp = (id) => request.delete(`/service/application/${id}`)

export const apiPage = (params) => request.get('/service/api/page', { params })
export const createApi = (data) => request.post('/service/api', data)
export const updateApi = (id, data) => request.put(`/service/api/${id}`, data)
export const publishApi = (id) => request.post(`/service/api/${id}/publish`)
export const offlineApi = (id) => request.post(`/service/api/${id}/offline`)
export const deleteApi = (id) => request.delete(`/service/api/${id}`)

// 数据治理
export const govCodeSetPage = (params) => request.get('/governance/codeset/page', { params })
export const createGovCodeSet = (data) => request.post('/governance/codeset', data)
export const updateGovCodeSet = (id, data) => request.put(`/governance/codeset/${id}`, data)
export const deleteGovCodeSet = (id) => request.delete(`/governance/codeset/${id}`)
export const govWordPage = (params) => request.get('/governance/word/page', { params })
export const createGovWord = (data) => request.post('/governance/word', data)
export const updateGovWord = (id, data) => request.put(`/governance/word/${id}`, data)
export const deleteGovWord = (id) => request.delete(`/governance/word/${id}`)
export const govLayerList = () => request.get('/governance/layer/list')
export const createGovLayer = (data) => request.post('/governance/layer', data)
export const updateGovLayer = (id, data) => request.put(`/governance/layer/${id}`, data)
export const deleteGovLayer = (id) => request.delete(`/governance/layer/${id}`)
export const govWhCatalogTree = (params) => request.get('/governance/warehouse-catalog/tree', { params })
export const createGovWhCatalog = (data) => request.post('/governance/warehouse-catalog', data)
export const deleteGovWhCatalog = (id) => request.delete(`/governance/warehouse-catalog/${id}`)
export const govModelPage = (params) => request.get('/governance/model/page', { params })
export const createGovModel = (data) => request.post('/governance/model', data)
export const updateGovModel = (id, data) => request.put(`/governance/model/${id}`, data)
export const deleteGovModel = (id) => request.delete(`/governance/model/${id}`)
export const govPeriodPage = (params) => request.get('/governance/period/page', { params })
export const createGovPeriod = (data) => request.post('/governance/period', data)
export const updateGovPeriod = (id, data) => request.put(`/governance/period/${id}`, data)
export const publishGovPeriod = (id) => request.post(`/governance/period/${id}/publish`)
export const deleteGovPeriod = (id) => request.delete(`/governance/period/${id}`)
export const govAtomicPage = (params) => request.get('/governance/atomic/page', { params })
export const createGovAtomic = (data) => request.post('/governance/atomic', data)
export const updateGovAtomic = (id, data) => request.put(`/governance/atomic/${id}`, data)
export const deleteGovAtomic = (id) => request.delete(`/governance/atomic/${id}`)
export const govLimitPage = (params) => request.get('/governance/limit/page', { params })
export const createGovLimit = (data) => request.post('/governance/limit', data)
export const updateGovLimit = (id, data) => request.put(`/governance/limit/${id}`, data)
export const deleteGovLimit = (id) => request.delete(`/governance/limit/${id}`)
export const govDerivedPage = (params) => request.get('/governance/derived/page', { params })
export const createGovDerived = (data) => request.post('/governance/derived', data)
export const updateGovDerived = (id, data) => request.put(`/governance/derived/${id}`, data)
export const deleteGovDerived = (id) => request.delete(`/governance/derived/${id}`)
export const govProxyPage = (params) => request.get('/governance/proxy/page', { params })
export const createGovProxy = (data) => request.post('/governance/proxy', data)
export const startGovProxy = (id) => request.post(`/governance/proxy/${id}/start`)
export const stopGovProxy = (id) => request.post(`/governance/proxy/${id}/stop`)
export const deleteGovProxy = (id) => request.delete(`/governance/proxy/${id}`)

// 数据开发
export const devProjectList = () => request.get('/development/project/list')
export const devWorkflowPage = (params) => request.get('/development/workflow/page', { params })
export const createDevWorkflow = (data) => request.post('/development/workflow', data)
export const updateDevWorkflow = (id, data) => request.put(`/development/workflow/${id}`, data)
export const runDevWorkflow = (id) => request.post(`/development/workflow/${id}/run`)
export const publishDevWorkflow = (id) => request.post(`/development/workflow/${id}/publish`)
export const deleteDevWorkflow = (id) => request.delete(`/development/workflow/${id}`)
export const devScriptPage = (params) => request.get('/development/script/page', { params })
export const createDevScript = (data) => request.post('/development/script', data)
export const updateDevScript = (id, data) => request.put(`/development/script/${id}`, data)
export const runDevScript = (id) => request.post(`/development/script/${id}/run`)
export const deleteDevScript = (id) => request.delete(`/development/script/${id}`)
export const devQualityTemplates = () => request.get('/development/quality/templates')
export const devQualityRulePage = (params) => request.get('/development/quality/rule/page', { params })
export const createDevQualityRule = (data) => request.post('/development/quality/rule', data)
export const deleteDevQualityRule = (id) => request.delete(`/development/quality/rule/${id}`)
export const devQualityTaskPage = (params) => request.get('/development/quality/task/page', { params })
export const createDevQualityTask = (data) => request.post('/development/quality/task', data)
export const executeDevQualityTask = (id) => request.post(`/development/quality/task/${id}/execute`)
export const devQualityOverview = () => request.get('/development/quality/overview')
export const devSchedulePage = (params) => request.get('/development/schedule/page', { params })
export const createDevSchedule = (data) => request.post('/development/schedule', data)
export const updateDevSchedule = (id, data) => request.put(`/development/schedule/${id}`, data)
export const startDevSchedule = (id) => request.post(`/development/schedule/${id}/start`)
export const stopDevSchedule = (id) => request.post(`/development/schedule/${id}/stop`)
export const deleteDevSchedule = (id) => request.delete(`/development/schedule/${id}`)

// 数据服务扩展
export const svcCatalogProjectList = () => request.get('/service/catalog-project/list')
export const svcCatalogTree = (params) => request.get('/service/catalog/tree', { params })
export const createSvcCatalog = (data) => request.post('/service/catalog', data)
export const deleteSvcCatalog = (id) => request.delete(`/service/catalog/${id}`)
export const svcUnitPage = (params) => request.get('/service/unit/page', { params })
export const createSvcUnit = (data) => request.post('/service/unit', data)
export const publishSvcUnit = (id) => request.post(`/service/unit/${id}/publish`)
export const offlineSvcUnit = (id) => request.post(`/service/unit/${id}/offline`)
export const deleteSvcUnit = (id) => request.delete(`/service/unit/${id}`)
export const svcWorkorderPage = (params) => request.get('/service/workorder/page', { params })
export const createSvcWorkorder = (data) => request.post('/service/workorder', data)
export const approveSvcWorkorder = (id, pass, reason) => request.post(`/service/workorder/${id}/approve`, null, { params: { pass, reason } })
export const svcRateLimitPage = (params) => request.get('/service/ratelimit/page', { params })
export const createSvcRateLimit = (data) => request.post('/service/ratelimit', data)
export const deleteSvcRateLimit = (id) => request.delete(`/service/ratelimit/${id}`)
export const svcMonitorStats = () => request.get('/service/monitor/stats')

// 数据资产
export const assetOverview = () => request.get('/asset/overview')
export const assetTablePage = (params) => request.get('/asset/table/page', { params })
export const assetTableDetail = (id) => request.get(`/asset/table/${id}`)
export const createAssetTable = (data) => request.post('/asset/table', data)
export const markKeyAsset = (id, isKey) => request.post(`/asset/table/${id}/mark-key`, null, { params: { isKey } })
export const deleteAssetTable = (id) => request.delete(`/asset/table/${id}`)
export const assetLineage = () => request.get('/asset/lineage')
export const assetMonitorStats = () => request.get('/asset/monitor/stats')

// 基础支撑
export const infraHostPage = (params) => request.get('/infrastructure/host/page', { params })
export const createInfraHost = (data) => request.post('/infrastructure/host', data)
export const deleteInfraHost = (id) => request.delete(`/infrastructure/host/${id}`)
export const infraComponentPage = (params) => request.get('/infrastructure/component/page', { params })
export const createInfraComponent = (data) => request.post('/infrastructure/component', data)
export const startInfraComponent = (id) => request.post(`/infrastructure/component/${id}/start`)
export const stopInfraComponent = (id) => request.post(`/infrastructure/component/${id}/stop`)
export const deleteInfraComponent = (id) => request.delete(`/infrastructure/component/${id}`)
export const infraClusterPage = (params) => request.get('/infrastructure/cluster/page', { params })
export const createInfraCluster = (data) => request.post('/infrastructure/cluster', data)
export const deleteInfraCluster = (id) => request.delete(`/infrastructure/cluster/${id}`)
export const infraDashboard = () => request.get('/infrastructure/dashboard')
